services:
  rss-bridge:
    container_name: rss-bridge
    build: .
#    image: rssbridge/rss-bridge:latest
    volumes:
      - ../config:/config
    ports:
      - 3000:80
    restart: unless-stopped